params:
  seed: 42
  env:
    clip_observations: 5.0
    # can make custom wrapper?
    clip_actions: 1.0
  algo:
    name: a2c_continuous
  model:
    name: continuous_a2c_logstd
  network:
    name: actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: -0.5
        fixed_sigma: False
    mlp:
      units: [1024, 512, 256]
      # units: [512, 256, 128]
      activation: elu
      d2rl: True
      initializer:
        name: default
      regularizer:
        name: None
  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load
  config:
    name: ${resolve_default:JugglingAgent,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    device: ${....rl_device}
    device_name: ${....rl_device}
    multi_gpu: ${....multi_gpu}
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: -1  # configured from the script (based on num_envs)
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.999 # original 0.99, make it higher to encourage long-term planning
    tau : 0.95
    learning_rate: 3e-4 # original 5e-4, make it a bit lower for stability
    lr_schedule: adaptive
    kl_threshold: 0.01
    score_to_win: 20000
    max_epochs: ${resolve_default:500,${....max_iterations}}
    save_best_after: 50
    save_frequency: 25
    grad_norm: 1.0
    entropy_coef: 0.01
    # entropy_schedule: [ # may need to customly add this, isaacgym does not have built-in support for entropy scheduling :(
    #   [0, 0.01],
    #   [500, 0.005],
    #   [750, 0.001]
    # ]
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 512
    # horizon_length: 128
    minibatch_size: 32768
    # minibatch_size: 65536
    # minibatch_size: 131072
    mini_epochs: 4
    critic_coef: 2
    clip_value: True
    # seq_length: 4
    bounds_loss_coef: 0.0001
  